package s_Demo;
import java.awt.Robot;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import org.apache.commons.io.FileUtils;
import org.openqa.selenium.By;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.OutputType;
import org.openqa.selenium.TakesScreenshot;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.chrome.ChromeDriver;



public class ORG_Task_Demo {
	public static void main(String[] args) throws InterruptedException, IOException, Throwable {
		WebDriver driver = new ChromeDriver();
		driver.manage().window().maximize();
		driver.get("https://opensource-demo.orangehrmlive.com/web/index.php/auth/login");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@name='username']")).sendKeys("Admin");
		driver.findElement(By.xpath("//input[@name='password']")).sendKeys("admin123");
		driver.findElement(By.xpath("//button[@type='submit']")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name'])[1]")).click();
		Thread.sleep(2000); 
	    driver.findElement(By.xpath("(//button[@type='button'])[5]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//i[@class='oxd-icon bi-caret-down-fill oxd-select-text--arrow'])[1]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//div[@role='option'])[2]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//input[@placeholder='Type for hints...']")).sendKeys("mohanraj");
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='mohanraj 26 8001']")).click();		
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//div[@class=\"oxd-select-text--after\"])[2]")).click();
		Thread.sleep(2000);
		driver.findElement(By.xpath("//*[text()='Enabled']")).click();
		driver.findElement(By.xpath("(//input[@autocomplete='off'])[1]")).sendKeys("mohanra");
		driver.findElement(By.xpath("(//input[@autocomplete='off'])[2]")).sendKeys("mohan2001");
		driver.findElement(By.xpath("(//input[@autocomplete='off'])[3]")).sendKeys("mohan2001");
     	driver.findElement(By.xpath("//button[@type='submit']")).click();
     	Thread.sleep(3000);
     	//------------------------
     	driver.findElement(By.xpath("(//*[@class='oxd-input oxd-input--active'])[2]")).sendKeys("mohanra");
     	Thread.sleep(3000);
     	driver.findElement(By.xpath("(//*[@class='oxd-icon bi-caret-down-fill oxd-select-text--arrow'])[1]")).click();
     	Thread.sleep(3000); 
     	Robot r =new Robot();
		r.keyPress(KeyEvent.VK_DOWN);
		r.keyRelease(KeyEvent.VK_DOWN);
		Thread.sleep(2000);
		r.keyPress(KeyEvent.VK_ENTER);
		r.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(3000);
        driver.findElement(By.xpath("//input[@placeholder='Type for hints...']")).sendKeys("mohan") ;
        Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='mohanraj 26 81']")).click();		
		Thread.sleep(3000);
     	driver.findElement(By.xpath("(//*[@class='oxd-icon bi-caret-down-fill oxd-select-text--arrow'])[2]")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Enabled']")).click();
     	driver.findElement(By.xpath("//button[@type='submit']")).click();
     	Thread.sleep(3000);
     	JavascriptExecutor jse=(JavascriptExecutor)driver;
     	jse.executeScript("window.scroll(2000,0)");
		Thread.sleep(4000);
		TakesScreenshot ts=(TakesScreenshot)driver;
		File screenshotAs = ts.getScreenshotAs(OutputType.FILE);
		File f=new File("C:\\Users\\user\\eclipse-workspace\\Seleniam_Demo\\ScreenShot\\Orange1.png");
		FileUtils.copyFile(screenshotAs, f);
		
	    Thread.sleep(3000);
		driver.findElement(By.xpath("//*[@id=\"app\"]/div[1]/div[1]/aside/nav/div[2]/ul/li[3]/a/span")).click();
		Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='Assign Leave']")).click();
	    Thread.sleep(3000);
        driver.findElement(By.xpath("//input[@placeholder='Type for hints...']")).sendKeys("mohan");
        Thread.sleep(3000);
		driver.findElement(By.xpath("//*[text()='mohanraj 26 81']")).click();		
        driver.findElement(By.xpath("//*[@class='oxd-select-text-input']")).click();
        Robot r2 =new Robot();
		r2.keyPress(KeyEvent.VK_DOWN);
		r2.keyRelease(KeyEvent.VK_DOWN);
		Thread.sleep(2000);
		r2.keyPress(KeyEvent.VK_DOWN);
		r2.keyRelease(KeyEvent.VK_DOWN);
		Thread.sleep(2000);
		r2.keyPress(KeyEvent.VK_ENTER);
		r2.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(2000);
		driver.findElement(By.xpath("(//*[@placeholder='yyyy-mm-dd'])[1]")).sendKeys("2023-12-29");
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//*[@placeholder='yyyy-mm-dd'])[2]")).sendKeys("");
		Thread.sleep(3000);
		driver.findElement(By.xpath("(//*[@class='oxd-select-text-input'])[2]")).click();
		Thread.sleep(2000);
		Robot r1 =new Robot();
		r1.keyPress(KeyEvent.VK_DOWN);
		r1.keyRelease(KeyEvent.VK_DOWN);
		Thread.sleep(2000);
		r1.keyPress(KeyEvent.VK_ENTER);
		r1.keyRelease(KeyEvent.VK_ENTER);
		Thread.sleep(3000);
//		driver.findElement(By.xpath("//*[@style='height: 77px;']")).sendKeys("leave");
//		Thread.sleep(2000);
		driver.findElement(By.xpath("//button[@type='submit']")).click();
		Thread.sleep(3000);
		TakesScreenshot ts1=(TakesScreenshot)driver;
		File screenshotAs1 = ts1.getScreenshotAs(OutputType.FILE);
		File f1=new File("C:\\Users\\user\\eclipse-workspace\\Seleniam_Demo\\ScreenShot\\Orange2.png");
		FileUtils.copyFile(screenshotAs1, f1);
        Thread.sleep(3000);
        driver.findElement(By.xpath("(//*[@type='button'])[4]")).click();
        Thread.sleep(3000);
		driver.findElement(By.xpath("(//span[@class='oxd-text oxd-text--span oxd-main-menu-item--name'])[5]")).click();
        Thread.sleep(3000);
        driver.findElement(By.xpath("(//button[@type='button'])[4]")).click();
        Thread.sleep(3000);
        driver.findElement(By.name("firstName")).sendKeys("mohanraj");
        Thread.sleep(3000);
        driver.findElement(By.name("middleName")).sendKeys("26");
        Thread.sleep(3000);
        driver.findElement(By.name("lastName")).sendKeys("81");
        Thread.sleep(3000);
        driver.findElement(By.xpath("//*[@class='oxd-select-text oxd-select-text--active']")).click();
		Thread.sleep(2000);
		Robot r3 =new Robot();
		r3.keyPress(KeyEvent.VK_DOWN);
		r3.keyRelease(KeyEvent.VK_DOWN);
		Thread.sleep(2000);
		r3.keyPress(KeyEvent.VK_ENTER);
		r3.keyRelease(KeyEvent.VK_ENTER);
        Thread.sleep(3000);
        WebElement gmail = driver.findElement(By.xpath("(//*[@class='oxd-input oxd-input--active'])[2]"));
        gmail.sendKeys("manikutty332001@gmail.com");
		Thread.sleep(3000);
		WebElement cell = driver.findElement(By.xpath("(//*[@class='oxd-input oxd-input--active'])[3]"));
        cell.sendKeys("7339294459");
        Thread.sleep(3000);
       // driver.findElement(By.xpath("(//*[@class='oxd-input oxd-input--active'])[4]")).sendKeys("7339294459");
      //  Thread.sleep(3000);
      //  driver.findElement(By.xpath("(//*[@class='oxd-input oxd-input--active'])[5]")).sendKeys("20-10-2022");
      //  Thread.sleep(3000);
        driver.findElement(By.xpath("(//*[@placeholder='Type here'])[3]")).sendKeys("hi");
        Thread.sleep(3000);
        driver.findElement(By.xpath("//*[@class='oxd-checkbox-input oxd-checkbox-input--active"
        		+ " --label-right oxd-checkbox-input']")).click();
        Thread.sleep(3000);
        driver.findElement(By.xpath("//*[@type='submit']")).click();
        Thread.sleep(8000);
        TakesScreenshot ts2=(TakesScreenshot)driver;
		File screenshotAs2 = ts2.getScreenshotAs(OutputType.FILE);
		File f2=new File("C:\\Users\\user\\eclipse-workspace\\Seleniam_Demo\\ScreenShot\\Orange3.png");
		FileUtils.copyFile(screenshotAs2, f2);
	}
}
